### PR TITLE
feat: Notfound page added

### PR DESCRIPTION
**Pull request by timrombergjakobsson**
Fixes: [CDEP-2256](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=CDEP-2256)

[CDEP-2256]: https://tegel.atlassian.net/browse/CDEP-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by timrombergjakobsson** [comment]
Build failing, on it!

**Review by nathalielindqvist — COMMENTED** [review]
Seems like there might be a spacing/layout issue here compared to the Angular 404 page? The content should have more margins in all directions when on large screen sizes
image

**Review by mJarsater — APPROVED** [review]

**Review by nathalielindqvist — CHANGES_REQUESTED** [review]
Seems like the Side Menu was lost and the content got pushed to the right?
image

image

**Comment by mJarsater** [comment]
Closed and continued in: https://github.com/scania-digital-design-system/tegel-react-demo/pull/132

**Pull request closed without merging**
