### PR TITLE
feat: consume React wrappers

### PR DESCRIPTION
**Pull request by nathalielindqvist**
Fixes: 
 - [CDEP-2679](https://tegel.atlassian.net/browse/CDEP-2679)
 - [CDEP-2835](https://tegel.atlassian.net/browse/CDEP-2835)

Implemented components
- [x] Accordion - Nathalie
- [x] Badge (components page) - Nathalie
- [x] Banner (components page) - Nathalie
- [x] Block - Nathalie
- [x] Breadcrumbs (components page) - Nathalie
- [x] Button (components page) - Nathalie
- [x] Card - Nathalie
- [x] Checkbox - Nathalie
- [x] Chip - Martin
- [x] Datetime - Nathalie
- [x] Divider - Nathalie
- [x] Dropdown - Nathalie
- [x] Link - Nathalie
- [x] Message - Nathalie
- [x] Modal - Nathalie
- [x] Popover Canvas - Nathalie
- [x] Popover Menu - Nathalie
- [x] Radio Button - Nathalie
- [x] Spinner - Martin
- [x] Stepper (components page) - Martin
- [x] Tabs (components page) - Martin
- [x] Text Field - Martin
- [x] Textarea - Martin
- [x] Toast - Martin
- [x] Toggle - Martin
- [x] Tooltip - Martin
- [x] Side Menu - Nathalie
- [x] Header - Nathalie
- [x] Footer - Nathalie
- [x] Breadcrumbs (navigation) - Nathalie
- [x] ModeSwitcher - Martin
- [x] ModeVariantSwitcher - Martin
- [x] Form page - Martin
- [x] Tabs button - Martin
- [x] Tabs link - Martin
- [x] Table page - Martin
- [x] Stepper page - Martin
- [x] User settings page - Martin
- [x] Notifications page - Martin

[CDEP-2679]: https://tegel.atlassian.net/browse/CDEP-2679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CDEP-2835]: https://tegel.atlassian.net/browse/CDEP-2835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by TatyanaBumazhkina** [comment]
Added bug ticket [CDEP-2835](https://tegel.atlassian.net/browse/CDEP-2835)

**Comment by TatyanaBumazhkina** [comment]
I've checked wrapper page, how components look like and interact. Look good to me.
Issue [CDEP-2835](https://tegel.atlassian.net/browse/CDEP-2835) has been fixed

**Review by alexandereneroth — APPROVED** [review]
Did a smoke test, and I think it looks good. 👍

**Comment by alexandereneroth** [comment]
Two other PRs are awaiting merge of this one

**Comment by mJarsater** [comment]
@nathalielindqvist  @alexandereneroth  I think this one can be merged?

**Review by timrombergjakobsson — APPROVED** [review]
Awesome work!

**Comment by alexandereneroth** [comment]
update: we said to await the release pipeline trial tomorrow

**Pull request merged**
