### PR TITLE
feat(popover-canvas): test referenceEl prop

### PR DESCRIPTION
**Pull request by alexandereneroth**
Tested that referenceEl works. 

Setting it directly on the tag with JSX does not work since non-react camelCase JSX properties will be lowercased and interpreted as attributes instead, should work when we have react wrappers though.

Using useEffect to set it imperatively worked though, as demonstrated here.

### CODE REVIEW

**Comment by mJarsater** [comment]
Nice find. However, should we have this prop available now, if it doesn't really work as we want it to? Or should we remove it and then bring it back before we release the wrappers?

**Comment by alexandereneroth** [comment]
> Nice find. However, should we have this prop available now, if it doesn't really work as we want it to? Or should we remove it and then bring it back before we release the wrappers?

Well, either way using React with our package is not a great experience in general. With the way you have to add event listeners etc.

I think we shouldn't have React dictate what we include in tegel or not, at least not before we have wrappers.

It does work well in vanilla html/js as well as Angular ATM.

Is it necessary at all when we also have selector? Maybe not, but I prefer passing the element directly(referenceEl), since it is less error prone than a text string and provides type safety

**Review by mJarsater — APPROVED** [review]

**Comment by alexandereneroth** [comment]
@nathalielindqvist waiting to merge these until you've had a look

**Review by nathalielindqvist — APPROVED** [review]
Works well, great job! 🥇

**Pull request merged**
